# Generated by Django 4.2.20 on 2025-05-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
